version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - db_bank
    links:
      - db_bank:nasabah
  mysql_db:
    image: "mysql:10.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_bank
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: